inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
 
Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 90
  Exclude:
    - 'bin/spring'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/assets.rb'
    - 'config/environments/production.rb'
    - 'config/environments/development.rb'
    - 'db/schema.rb'

Metrics/MethodLength:
  Max: 15

Style/IndentationConsistency:
  Enabled: false
  
Style/AlignHash:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ExtraSpacing:
  Exclude:
    - 'bin/setup'
    - 'db/schema.rb'

Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/HashSyntax:
  Exclude:
    - 'db/migrate/20160710050207_create_friendly_id_slugs.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'config/initializers/rack_attack.rb'

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Lint/Eval:
  Exclude:
    - 'app/models/album.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/album.rb'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'app/models/album.rb'

