AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'

AccessModifierIndentation:
  EnforcedStyle: outdent

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 9

Metrics/LineLength:
  Max: 90
  Exclude:
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/assets.rb'
    - 'config/environments/production.rb'
    - 'config/environments/development.rb'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'app/views/*/*.json.jbuilder'
    - 'app/views/*/*/*.json.jbuilder'

Metrics/MethodLength:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/AbcSize:
  Max: 26

Layout/IndentationConsistency:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/IndentHeredoc:
    Enabled: false

Layout/ExtraSpacing:
  Exclude:
    - 'db/schema.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/WordArray:
  Exclude:
    - 'db/schema.rb'

Style/HashSyntax:
  Exclude:
    - 'db/migrate/20160710050207_create_friendly_id_slugs.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'config/initializers/rack_attack.rb'

Style/SymbolProc:
  Exclude:
    - 'config/initializers/rack_attack.rb'
    - 'config/routes.rb'

Style/ExpandPathArguments:
  Exclude:
    - 'config/boot.rb'
    - 'spec/rails_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'db/*.rb'
    - 'spec/**/*.rb'

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'
