inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
 
Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 90
  Exclude:
    - 'bin/spring'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/assets.rb'
    - 'config/environments/production.rb'
    - 'config/environments/development.rb'
    - 'db/schema.rb'

Style/IndentationConsistency:
  Enabled: false
  
Style/AlignHash:
  Enabled: false

Style/Lambda:
  Enabled: false

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Lint/Eval:
  Exclude:
    - 'app/models/album.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/album.rb'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'app/models/album.rb'

