inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
 
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'app/models/album.rb'

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Lint/Eval:
  Exclude:
    - 'app/models/album.rb'
