default: &default
  adapter: postgresql
  encoding: unicode
  pool: 8
  timeout: 5000

development:
  <<: *default
  database: platters_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: platters_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: platters_production
  username: <%= ENV["PG_PLATTERS_USERNAME"] %>
  password: <%= ENV["PG_PLATTERS_PASSWORD"] %>
