default: &default
  adapter: postgresql
  encoding: unicode
  pool: 8
  timeout: 5000

development:
  <<: *default
  database: platters_development

test:
  <<: *default
  database: platters_test

production:
  <<: *default
  database: platters_production
  username: <%= ENV["PG_PLATTERS_USERNAME"] %>
  password: <%= ENV["PG_PLATTERS_PASSWORD"] %>
